#SPDX-License-Identifier: MIT-0
---
# Role-specific defaults
win_join_state: domain        # domain | workgroup
win_join_reboot: true
win_join_workgroup: WORKGROUP # workgroup name used when state=workgroup

# Shared with build_dc — override in inventory if needed
samba_ad_dc_administrator_username: admin
samba_ad_dc_administrator_passwd: "{{ ansible_password }}"
samba_ad_dc_realm: ~
samba_ad_dc_search_domain: ~
