#SPDX-License-Identifier: MIT-0
---
- name: Make sure all required variables are defined
  ansible.builtin.assert:
    that:
      - samba_ad_dc_realm | default("", true) | length > 0
      - samba_ad_dc_domain | default("", true) | length > 0
      - samba_ad_dc_fqdn | default("", true) | length > 0
      - samba_ad_dc_search_domain | default("", true) | length > 0
      - samba_ad_dc_nameserver | default("", true) | length > 0
      - samba_ad_dc_address | default("", true) | length > 0
      - samba_ad_dc_netmask | default("", true) | length > 0
      - samba_ad_dc_gateway | default("", true) | length > 0
      - samba_ad_dc_ifname | default("", true) | length > 0
      - samba_ad_dc_ntp_server | default("", true) | length > 0
      - samba_ad_dc_ntp_allow_network | default("", true) | length > 0
      - samba_ad_dc_administrator_passwd | default("", true) | length > 0
    fail_msg: |
      Missing or null required variables in the samba_ad_dc role.
      Verify that host_vars/{{ inventory_hostname }}.yaml contains all samba_ad_dc_* variables.
      Required variables: realm, domain, fqdn, search_domain, nameserver, address, netmask,
      gateway, ifname, ntp_server, ntp_allow_network, administrator_passwd.
    quiet: true
