# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Copy /etc/krb5.conf to /etc/krb5.conf.dist if it doesn't already exist
  ansible.builtin.copy:
    src: /etc/krb5.conf
    dest: /etc/krb5.conf.dist
    remote_src: true
    force: false
    mode: "0644"

- name: Check the status of /etc/krb5.conf
  ansible.builtin.stat:
    path: /etc/krb5.conf
    follow: false # importante per sapere se è un symlink
  register: build_dc_krb5_status

- name: Delete the Kerberos configuration file if it is a normal file
  ansible.builtin.file:
    path: /etc/krb5.conf
    state: absent
  when: build_dc_krb5_status.stat.exists and not build_dc_krb5_status.stat.islnk

- name: Create a symbolic link
  ansible.builtin.file:
    src: /var/lib/samba/private/krb5.conf
    dest: /etc/krb5.conf
    state: link
