# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Check if Administrator password has already been set
  ansible.builtin.stat:
    path: /var/lib/samba/.administrator_password_set
  register: build_dc_admin_passwd_set

- name: Set Administrator password
  ansible.builtin.shell: |
    samba-tool user setpassword "$SAMBA_ADMIN_USER" --newpassword="$SAMBA_ADMIN_PASS"
  environment:
    SAMBA_ADMIN_PASS: "{{ build_dc_administrator_passwd }}"
    SAMBA_ADMIN_USER: "Administrator"
  no_log: true
  changed_when: true
  when: not build_dc_admin_passwd_set.stat.exists

- name: Mark Administrator password as set
  ansible.builtin.file:
    path: /var/lib/samba/.administrator_password_set
    state: touch
    owner: root
    group: root
    mode: "0600"
  when: not build_dc_admin_passwd_set.stat.exists
