# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Make sure all required variables are defined
  ansible.builtin.assert:
    that:
      - samba_dc_build_realm | default("", true) | length > 0
      - samba_dc_build_domain | default("", true) | length > 0
      - samba_dc_build_fqdn | default("", true) | length > 0
      - samba_dc_build_search_domain | default("", true) | length > 0
      - samba_dc_build_nameserver | default("", true) | length > 0
      - samba_dc_build_address | default("", true) | length > 0
      - samba_dc_build_netmask | default("", true) | length > 0
      - samba_dc_build_gateway | default("", true) | length > 0
      - samba_dc_build_ifname | default("", true) | length > 0
      - samba_dc_build_ntp_server | default("", true) | length > 0
      - samba_dc_build_ntp_allow_network | default("", true) | length > 0
      - samba_dc_build_administrator_passwd | default("", true) | length > 0
    fail_msg: |
      Missing or null required variables in the samba_dc_build role.
      Verify that host_vars/{{ inventory_hostname }}.yaml contains all samba_dc_build_* variables.
      Required variables: realm, domain, fqdn, search_domain, nameserver, address, netmask,
      gateway, ifname, ntp_server, ntp_allow_network, administrator_passwd.
    quiet: true
