# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Reboot the system
  ansible.builtin.reboot:
  listen: samba_ad_dc reboot

- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded
  listen: samba_ad_dc reload nftables

- name: Restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted
  listen: samba_ad_dc restart chrony
